version: '2'
services:
    avalanchetests-app:
        image: avalanchetests
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://avalanchetests-postgresql:5432/avalancheTests
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    avalanchetests-postgresql:
        extends:
            file: postgresql.yml
            service: avalanchetests-postgresql
